# -*- coding: utf-8 -*-
"""python_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjTPbLEmqTH7pDTlHRe8Mi7hQxekd8u3

# **Print**
"""

print("Hello world")

print(26)

#this is a comment
print("I learn comment")

"""## **Data Type**

# **String Methods**
"""

#print the data type
type("This is string")

#to conver string to upper case
print("This is string".upper())

"Hello".upper()

#for count the carecter in a string or scentence
"Hello".count('l')#we are counting l in hello

#if we do not write print it will just print the last one only .
print("This is string".upper())
print("This is string".lower())
print("This is string".title())

"Hello".replace('o','u') #we are replacing o with u

"""# **Variables**"""

x="this is a 1st variable"

x

y=" and this is the 2nd one"

y

x+y

#this is call f string
f'{x}we are connecting this 2 variable {y}'

f'{x} we are connecting this 2 variable {y}'

x+' '+y

"""# **List**"""

